import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createApp } from './app.js';
import { SimulatorObserver } from './simulator.js';
import { readStoredState } from './test-helpers.js';

test('local API persists owner notes and never claims robot evidence',async t=>{
  const folder=await mkdtemp(path.join(os.tmpdir(),'ducktown-test-'));
  const dataFile=path.join(folder,'data.json');
  t.after(()=>rm(folder,{recursive:true,force:true}));
  await writeFile(dataFile,JSON.stringify({version:1,robots:[{id:'pepper',name:'Pepper',mode:'simulation',hardwareConnected:false,owner:'local-demo'}],posts:[{id:'legacy',name:'Pepper’s human',origin:'owner_note',text:'Old demo note'}]}));
  const {server}=await createApp({dataFile,simulator:new SimulatorObserver({root:null})});
  server.listen(0,'127.0.0.1');
  await new Promise(resolve=>server.once('listening',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  const health=await (await fetch(`${base}/api/v1/health`)).json();
  assert.equal(health.hardwareConnected,false);
  assert.equal((await (await fetch(`${base}/api/v1/robots/pepper`)).json()).robot.mode,'simulation');
  const catalog=await (await fetch(`${base}/api/v1/behaviors`)).json();
  assert.equal(catalog.behaviors.length,11);
  assert.ok(catalog.behaviors.every(item=>item.verification==='unverified'));
  assert.equal((await (await fetch(`${base}/api/v1/posts`)).json()).posts[0].id,'legacy');
  assert.equal((await (await fetch(`${base}/api/v1/auth/me`)).json()).user,null);
  assert.equal((await fetch(`${base}/api/v1/simulator/status`)).status,401);
  assert.equal((await fetch(`${base}/api/v1/installed-policies`)).status,401);
  assert.equal((await fetch(`${base}/api/v1/sdk-observations`)).status,401);
  assert.equal((await fetch(`${base}/api/v1/posts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:'No session'})})).status,401);
  const register=await fetch(`${base}/api/v1/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle:'builder_one',password:'long-enough-secret-one'})});
  assert.equal(register.status,201);
  const cookie=register.headers.get('set-cookie').split(';')[0];
  assert.match(register.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);
  const account=await register.json();
  assert.equal(account.user.handle,'builder_one');
  assert.equal(account.robot.ownerId,account.user.id);
  assert.equal(account.robot.hardwareConnected,false);
  assert.equal((await (await fetch(`${base}/api/v1/auth/me`,{headers:{Cookie:cookie}})).json()).user.id,account.user.id);
  const sim=await (await fetch(`${base}/api/v1/simulator/status`,{headers:{Cookie:cookie}})).json();
  assert.equal(sim.verifiedRun,false);
  assert.equal((await fetch(`${base}/api/v1/installed-policies`,{headers:{Cookie:cookie}})).status,503);
  assert.equal((await fetch(`${base}/api/v1/sdk-observations`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:'{}'})).status,409);
  assert.deepEqual((await (await fetch(`${base}/api/v1/sdk-observations`,{headers:{Cookie:cookie}})).json()).observations,[]);
  assert.equal((await fetch(`${base}/api/v1/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle:'builder_one',password:'long-enough-secret-one'})})).status,409);
  const register2=await fetch(`${base}/api/v1/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle:'builder_two',password:'long-enough-secret-two'})});
  const other=await register2.json();
  assert.equal((await fetch(`${base}/api/v1/posts`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({text:'Wrong robot',robotId:other.robot.id})})).status,403);
  const postResponse=await fetch(`${base}/api/v1/posts`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({text:'A small build note <script>\nNo robot ran.'})});
  assert.equal(postResponse.status,201);
  const {post}=await postResponse.json();
  assert.equal(post.origin,'owner_note');
  assert.equal(post.userId,account.user.id);
  assert.equal(post.robotId,account.robot.id);
  assert.match(post.receipt,/not robot evidence/);
  assert.equal(post.text,'A small build note <script>\nNo robot ran.');
  assert.equal((await (await fetch(`${base}/api/v1/posts`)).json()).posts[0].id,post.id);
  assert.equal(readStoredState(dataFile).posts[1].id,post.id);
  assert.equal((await fetch(`${base}/api/v1/posts`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({text:' '})})).status,400);
  assert.equal((await fetch(`${base}/api/v1/posts`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({text:'x'.repeat(801)})})).status,400);
  assert.equal((await fetch(`${base}/api/v1/posts`,{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://example.com'},body:JSON.stringify({text:'bad origin'})})).status,403);
  const logout=await fetch(`${base}/api/v1/auth/logout`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:'{}'});
  assert.equal(logout.status,200);
  assert.equal((await (await fetch(`${base}/api/v1/auth/me`,{headers:{Cookie:cookie}})).json()).user,null);
  const badLogin=await fetch(`${base}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle:'builder_one',password:'wrong-password'})});
  assert.equal(badLogin.status,401);
  const login=await fetch(`${base}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle:'builder_one',password:'long-enough-secret-one'})});
  assert.equal(login.status,200);
  const landing=await fetch(`${base}/`);
  assert.equal(landing.status,200);
  assert.match(await landing.text(),/Ducktown/);
  assert.equal((await fetch(`${base}/ducktown.html`)).status,200);
  assert.equal((await fetch(`${base}/api/v1/not-found`)).status,404);
  const stored=readStoredState(dataFile);
  assert.equal(stored.posts[0].id,'legacy');
  assert.equal(stored.users.length,2);
  assert.ok(!JSON.stringify(stored).includes('long-enough-secret-one'));
});

test('SDK observations are private, explicit, and never run receipts',async t=>{
  const folder=await mkdtemp(path.join(os.tmpdir(),'ducktown-sdk-test-'));
  t.after(()=>rm(folder,{recursive:true,force:true}));
  const policyJson=JSON.stringify({policies:{mode:'idle',enabled:true,slots:[{slot:'locomotion',path:'walk.onnx',origin:'bundled',overridden:false,error:null}],skills:['kick_left']},skills:{skills:[{name:'kick_left',path:'kick_left.onnx',duration:2.1}],built_in:['sit_toggle']}});
  const simulator={snapshot:async()=>({ready:true,observation:{type:'sdk_observation',source:'configured_duck_sim_cli',verification:'unverified',isRun:false,hardwareConnected:false,observedAt:new Date().toISOString(),policyListOutput:policyJson,versionOutput:'dev',checks:{policies:{ok:true,outputSha256:'a'.repeat(64)}}}}),inspect:async()=>({configured:true,ok:true,source:'configured_duck_sim_cli',checkedAt:new Date().toISOString(),output:policyJson})};
  const {server}=await createApp({dataFile:path.join(folder,'data.json'),simulator});
  server.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  const register=async(handle,password)=>{
    const response=await fetch(`${base}/api/v1/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle,password})});
    assert.equal(response.status,201);return response.headers.get('set-cookie').split(';')[0];
  };
  const alice=await register('observer_one','observer-secret-one');
  const bob=await register('observer_two','observer-secret-two');
  const installedResponse=await fetch(`${base}/api/v1/installed-policies`,{headers:{Cookie:alice}});
  assert.equal(installedResponse.status,200);
  const installed=await installedResponse.json();
  assert.equal(installed.verification,'sdk_reported_only');
  assert.equal(installed.isRun,false);
  assert.equal(installed.slots[0].path,'walk.onnx');
  assert.equal(installed.skills[0].name,'kick_left');
  assert.deepEqual(installed.builtIn,[{name:'sit_toggle',kind:'daemon_built_in'}]);
  const capture=await fetch(`${base}/api/v1/sdk-observations`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:alice},body:'{}'});
  assert.equal(capture.status,201);
  const {observation}=await capture.json();
  assert.equal(observation.isRun,false);
  assert.equal(observation.verification,'unverified');
  assert.equal((await (await fetch(`${base}/api/v1/sdk-observations`,{headers:{Cookie:alice}})).json()).observations.length,1);
  assert.equal((await (await fetch(`${base}/api/v1/sdk-observations`,{headers:{Cookie:bob}})).json()).observations.length,0);
  assert.equal((await fetch(`${base}/api/v1/sdk-observations`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);
});
