import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createApp } from './app.js';
import { readStoredState } from './test-helpers.js';
import { Store } from './store.js';

test('two store connections serialize writes without losing either account',async t=>{
  const folder=await mkdtemp(path.join(os.tmpdir(),'ducktown-db-concurrent-'));
  t.after(()=>rm(folder,{recursive:true,force:true}));
  const dataFile=path.join(folder,'town.json'),one=new Store(dataFile),two=new Store(dataFile);
  await one.open();await two.open();
  t.after(()=>{one.close();two.close();});
  await Promise.all([one.createUser('first_duck','test-hash'),two.createUser('other_duck','test-hash')]);
  one.refresh();two.refresh();
  assert.equal(one.state.users.length,2);
  assert.equal(two.state.users.length,2);
  assert.equal(readStoredState(dataFile).users.length,2);
});

test('profiles, follows, saves, and notifications survive restart with owner boundaries',async t=>{
  const folder=await mkdtemp(path.join(os.tmpdir(),'ducktown-community-'));
  t.after(()=>rm(folder,{recursive:true,force:true}));
  const dataFile=path.join(folder,'town.json');
  await writeFile(dataFile,JSON.stringify({version:1,robots:[{id:'pepper',name:'Pepper',mode:'simulation',hardwareConnected:false,owner:'local-demo'}],posts:[]}));
  const start=async()=>{const app=await createApp({dataFile});app.server.listen(0,'127.0.0.1');await new Promise(resolve=>app.server.once('listening',resolve));return {app,base:`http://127.0.0.1:${app.server.address().port}`};};
  let {app,base}=await start();
  t.after(()=>new Promise(resolve=>app.server.close(resolve)));
  const request=(route,method='GET',body,cookie)=>fetch(`${base}${route}`,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const register=async handle=>{const response=await request('/api/v1/auth/register','POST',{handle,password:`very-long-${handle}-password`});assert.equal(response.status,201);return {cookie:response.headers.get('set-cookie').split(';')[0],...(await response.json())};};
  const alice=await register('flock_alice'),bob=await register('flock_bob');
  assert.equal((await request('/api/v1/profile','PUT',{},alice.cookie)).status,400);
  assert.equal((await request('/api/v1/profile','PUT',{name:'<script>',bio:'Hi',colorway:'cream',publicProfile:true,ownerId:bob.user.id},alice.cookie)).status,400);
  assert.equal((await request('/api/v1/profile','PUT',{name:'A'.repeat(41),bio:'Hi',colorway:'cream',publicProfile:true},alice.cookie)).status,400);
  const profile={name:'Amber',bio:'Curious about tiny dances <3',colorway:'lavender',publicProfile:true};
  const changed=await request('/api/v1/profile','PUT',profile,alice.cookie);
  assert.equal(changed.status,200);assert.equal((await changed.json()).profile.name,'Amber');
  assert.equal((await request('/api/v1/profiles/flock_alice/follow','PUT',undefined,alice.cookie)).status,400);
  assert.equal((await request('/api/v1/profiles/flock_alice/follow','PUT',undefined,bob.cookie)).status,200);
  assert.equal((await request('/api/v1/profiles/flock_alice/follow','PUT',undefined,bob.cookie)).status,200);
  assert.equal((await (await request('/api/v1/profiles/flock_alice')).json()).profile.followers,1);
  assert.equal((await request('/api/v1/saves/idea/not-real','PUT',undefined,bob.cookie)).status,404);
  assert.equal((await request('/api/v1/saves/idea/polite-bow','PUT',undefined,bob.cookie)).status,200);
  assert.equal((await request('/api/v1/saves/challenge/greeting','PUT',undefined,bob.cookie)).status,200);
  const post=(await (await request('/api/v1/posts','POST',{text:'A real build note'},alice.cookie)).json()).post;
  assert.equal((await request(`/api/v1/saves/post/${post.id}`,'PUT',undefined,bob.cookie)).status,200);
  assert.equal((await request(`/api/v1/posts/${post.id}/replies`,'POST',{text:'Welcome!'},bob.cookie)).status,201);
  const aliceNotices=(await (await request('/api/v1/notifications','GET',undefined,alice.cookie)).json()).notifications;
  assert.deepEqual(aliceNotices.map(item=>item.kind),['reply','follow']);
  assert.equal((await (await request('/api/v1/notifications','GET',undefined,bob.cookie)).json()).notifications.length,0);
  assert.equal((await request('/api/v1/notifications/read','POST',{},bob.cookie)).status,200);
  assert.equal((await request('/api/v1/notifications/read','POST',{},alice.cookie)).status,200);
  assert.ok((await (await request('/api/v1/notifications','GET',undefined,alice.cookie)).json()).notifications.every(item=>item.read));
  const privateProfile={...profile,publicProfile:false};
  assert.equal((await request('/api/v1/profile','PUT',privateProfile,alice.cookie)).status,200);
  assert.equal((await request('/api/v1/profiles/flock_alice')).status,404);
  assert.equal((await request('/api/v1/profiles/flock_alice','GET',undefined,alice.cookie)).status,200);
  assert.equal((await request('/api/v1/profiles/flock_alice/follow','PUT',undefined,bob.cookie)).status,404);
  assert.equal((await (await request('/api/v1/following','GET',undefined,bob.cookie)).json()).following[0].private,true);
  assert.equal((await request('/api/v1/profiles/flock_alice/follow','DELETE',undefined,bob.cookie)).status,200);
  assert.equal((await (await request('/api/v1/following','GET',undefined,bob.cookie)).json()).following.length,0);
  assert.ok(!(await (await request('/api/v1/profiles')).json()).profiles.some(item=>item.handle==='flock_alice'));
  assert.equal((await request('/api/v1/robots/'+alice.robot.id)).status,404);
  assert.equal((await request('/api/v1/robots/'+alice.robot.id,'GET',undefined,alice.cookie)).status,200);
  assert.equal((await (await request('/api/v1/posts')).json()).posts[0].id,post.id);
  assert.equal((await request('/api/v1/saves','GET',undefined,bob.cookie)).status,200);
  assert.equal((await request('/api/v1/saves','GET')).status,401);
  await new Promise(resolve=>app.server.close(resolve));
  ({app,base}=await start());
  assert.equal((await (await request('/api/v1/auth/me','GET',undefined,alice.cookie)).json()).robot.name,'Amber');
  assert.equal((await (await request('/api/v1/saves','GET',undefined,bob.cookie)).json()).saves.length,3);
  assert.equal((await (await request('/api/v1/notifications','GET',undefined,alice.cookie)).json()).notifications.length,2);
  assert.equal(readStoredState(dataFile).follows.length,0);
  assert.equal(JSON.parse(await readFile(dataFile,'utf8')).posts.length,0,'legacy JSON is an import source, not the active store');
});

test('recovery codes are single-use, rotated, and revoke existing sessions',async t=>{
  const folder=await mkdtemp(path.join(os.tmpdir(),'ducktown-recovery-'));
  t.after(()=>rm(folder,{recursive:true,force:true}));
  const dataFile=path.join(folder,'town.json'),{server}=await createApp({dataFile});
  server.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  const send=(route,body,cookie)=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(body)});
  const registered=await send('/api/v1/auth/register',{handle:'recover_me',password:'first-long-password'});
  assert.equal(registered.status,201);
  const cookie=registered.headers.get('set-cookie').split(';')[0],{recoveryCode}=await registered.json();
  assert.ok(recoveryCode.length>30);
  assert.ok(!JSON.stringify(readStoredState(dataFile)).includes(recoveryCode));
  assert.equal((await send('/api/v1/auth/recovery-code',{password:'wrong'},cookie)).status,401);
  const rotated=await send('/api/v1/auth/recovery-code',{password:'first-long-password'},cookie);
  assert.equal(rotated.status,200);
  const newCode=(await rotated.json()).recoveryCode;
  assert.notEqual(newCode,recoveryCode);
  assert.equal((await send('/api/v1/auth/recover',{handle:'recover_me',recoveryCode,newPassword:'second-long-password'})).status,401);
  assert.equal((await send('/api/v1/auth/recover',{handle:'recover_me',recoveryCode:newCode,newPassword:'short'})).status,400);
  const recovered=await send('/api/v1/auth/recover',{handle:'recover_me',recoveryCode:newCode,newPassword:'second-long-password'});
  assert.equal(recovered.status,200);
  const finalCode=(await recovered.json()).recoveryCode;
  assert.notEqual(finalCode,newCode);
  assert.equal((await (await fetch(base+'/api/v1/auth/me',{headers:{Cookie:cookie}})).json()).user,null);
  assert.equal((await send('/api/v1/auth/login',{handle:'recover_me',password:'first-long-password'})).status,401);
  assert.equal((await send('/api/v1/auth/login',{handle:'recover_me',password:'second-long-password'})).status,200);
  assert.equal((await send('/api/v1/auth/recover',{handle:'recover_me',recoveryCode:newCode,newPassword:'third-long-password'})).status,401);
  assert.ok(!JSON.stringify(readStoredState(dataFile)).includes(finalCode));
});

test('reported posts can be hidden and restored only by the local operator',async t=>{
  const folder=await mkdtemp(path.join(os.tmpdir(),'ducktown-report-'));
  t.after(()=>rm(folder,{recursive:true,force:true}));
  const dataFile=path.join(folder,'town.json'),{server}=await createApp({dataFile});
  server.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  const send=(route,method='GET',body,headers={})=>fetch(base+route,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const register=async handle=>{const response=await send('/api/v1/auth/register','POST',{handle,password:`super-long-${handle}-password`});return response.headers.get('set-cookie').split(';')[0];};
  const owner=await register('report_owner'),reporter=await register('report_reader');
  const post=(await (await send('/api/v1/posts','POST',{text:'A post to review'},{Cookie:owner})).json()).post;
  const reply=(await (await send(`/api/v1/posts/${post.id}/replies`,'POST',{text:'A reply to review'},{Cookie:reporter})).json()).reply;
  assert.equal((await send(`/api/v1/replies/${reply.id}/report`,'POST',{reason:'harassment'},{Cookie:owner})).status,200);
  const route=`/api/v1/posts/${post.id}/report`;
  assert.equal((await send(route,'POST',{reason:'spam'})).status,401);
  assert.equal((await send(route,'POST',{reason:'invented'},{Cookie:reporter})).status,400);
  assert.equal((await send(route,'POST',{reason:'spam'},{Cookie:reporter})).status,200);
  assert.equal((await send(route,'POST',{reason:'spam'},{Cookie:reporter})).status,200);
  assert.equal(readStoredState(dataFile).reports.length,2);
  assert.equal((await send('/api/v1/operator/reports')).status,403);
  const token=(await readFile(`${dataFile}.operator-token`,'utf8')).trim();
  const auth={Authorization:`Bearer ${token}`};
  const reports=(await (await send('/api/v1/operator/reports','GET',undefined,auth)).json()).reports;
  assert.deepEqual(reports.map(item=>item.reason),['harassment','spam']);
  assert.equal((await send('/api/v1/operator/moderate-reply','POST',{replyId:reply.id,hidden:true},auth)).status,200);
  assert.equal((await (await send(`/api/v1/posts/${post.id}/replies`)).json()).replies.length,0);
  assert.equal((await (await send('/api/v1/posts')).json()).posts[0].replies,0);
  assert.equal((await send(`/api/v1/replies/${reply.id}/report`,'POST',{reason:'spam'},{Cookie:owner})).status,404);
  assert.equal((await send('/api/v1/operator/moderate-reply','POST',{replyId:reply.id,hidden:false},auth)).status,200);
  assert.equal((await (await send(`/api/v1/posts/${post.id}/replies`)).json()).replies.length,1);
  assert.equal((await send('/api/v1/operator/moderate-post','POST',{postId:post.id,hidden:true})).status,403);
  assert.equal((await send('/api/v1/operator/moderate-post','POST',{postId:post.id,hidden:true,score:100},auth)).status,400);
  assert.equal((await send('/api/v1/operator/moderate-post','POST',{postId:post.id,hidden:true},auth)).status,200);
  assert.equal((await (await send('/api/v1/posts')).json()).posts.length,0);
  assert.equal((await send(`/api/v1/posts/${post.id}/replies`)).status,404);
  assert.equal((await send(`/api/v1/posts/${post.id}/like`,'PUT',undefined,{Cookie:reporter})).status,404);
  assert.equal((await send(`/api/v1/saves/post/${post.id}`,'PUT',undefined,{Cookie:reporter})).status,404);
  assert.equal((await send('/api/v1/operator/moderate-post','POST',{postId:post.id,hidden:false},auth)).status,200);
  assert.equal((await (await send('/api/v1/posts')).json()).posts[0].id,post.id);
});
