import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createApp } from './app.js';

test('installed-policy route fails closed for unavailable, malformed, and unauthorized SDK output',async t=>{
  const folder=await mkdtemp(path.join(os.tmpdir(),'ducktown-policy-route-'));
  t.after(()=>rm(folder,{recursive:true,force:true}));
  let reading={configured:false,ok:false,reason:'No official checkout'};
  const simulator={inspect:async command=>{assert.equal(command,'policies');return reading;},snapshot:async()=>({ready:false,reason:'No official checkout'})};
  const {server}=await createApp({dataFile:path.join(folder,'data.json'),simulator});
  server.listen(0,'127.0.0.1');
  await new Promise(resolve=>server.once('listening',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  assert.equal((await fetch(`${base}/api/v1/installed-policies`)).status,401);
  const registration=await fetch(`${base}/api/v1/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle:'policy_tester',password:'long-policy-test-secret'})});
  assert.equal(registration.status,201);
  const cookie=registration.headers.get('set-cookie').split(';')[0];
  const get=()=>fetch(`${base}/api/v1/installed-policies`,{headers:{Cookie:cookie}});
  let response=await get();
  assert.equal(response.status,503);
  assert.match((await response.json()).reason,/No official checkout/);
  reading={configured:true,ok:false,reason:'Check timed out',checkedAt:new Date().toISOString()};
  response=await get();
  assert.equal(response.status,503);
  assert.match((await response.json()).reason,/timed out/);
  reading={configured:true,ok:true,output:'{"policies":',source:'configured_duck_sim_cli',checkedAt:new Date().toISOString()};
  response=await get();
  assert.equal(response.status,502);
  assert.match((await response.json()).error,/not valid JSON/);
  reading={...reading,output:JSON.stringify({policies:{mode:'idle',enabled:true,slots:[]},skills:{skills:[],built_in:[]}})};
  response=await get();
  assert.equal(response.status,200);
  const body=await response.json();
  assert.equal(body.verification,'sdk_reported_only');
  assert.equal(body.isRun,false);
  assert.equal(body.hardwareConnected,false);
  assert.deepEqual(body.slots,[]);
});
