import test from 'node:test';
import assert from 'node:assert/strict';
import { SimulatorObserver } from './simulator.js';

test('official simulator observer is read-only and never manufactures a run',async()=>{
  const absent=await new SimulatorObserver({root:null}).inspect('status');
  assert.equal(absent.configured,false);
  assert.equal(absent.verifiedRun,false);
  const calls=[];
  const observer=new SimulatorObserver({root:'/official/microduck',checkExecutable:async()=>true,runner:async(file,args,options)=>{calls.push({file,args,options});return {stdout:'robot     healthy\n'};}});
  const result=await observer.inspect('health');
  assert.equal(result.ok,true);
  assert.equal(result.output,'robot     healthy');
  assert.equal(result.hardwareConnected,false);
  assert.equal(result.verifiedRun,false);
  assert.deepEqual(calls[0].args,['ctl','health','--json']);
  assert.equal(calls[0].file,'/official/microduck/scripts/duck-sim');
  assert.equal(calls[0].options.timeout,8000);
  await assert.rejects(()=>observer.inspect('drive'),{status:404});
  await assert.rejects(()=>observer.inspect('up'),{status:404});
  await assert.rejects(()=>observer.inspect('ctl policy load'),{status:404});
  assert.equal(calls.length,1);
  calls.length=0;
  const snapshot=await observer.snapshot();
  assert.equal(snapshot.ready,true);
  assert.equal(snapshot.observation.type,'sdk_observation');
  assert.equal(snapshot.observation.verification,'unverified');
  assert.equal(snapshot.observation.isRun,false);
  assert.equal(snapshot.observation.hardwareConnected,false);
  assert.deepEqual(calls.map(item=>item.args),[['status'],['ctl','health','--json'],['ctl','policy','list','--json'],['ctl','version'],['realtime']]);
  assert.match(snapshot.observation.checks.policies.outputSha256,/^[a-f0-9]{64}$/);
  const failure=new SimulatorObserver({root:'/official/microduck',checkExecutable:async()=>true,runner:async()=>{throw Object.assign(new Error('failed'),{code:2,stdout:'unhealthy'});}});
  const failed=await failure.inspect('status');
  assert.equal(failed.ok,false);
  assert.equal(failed.exitCode,2);
  assert.equal(failed.verifiedRun,false);
  const refused=await failure.snapshot();
  assert.equal(refused.ready,false);
  assert.equal(refused.failedCheck,'status');
});

test('observer fails closed on missing executable, daemon errors, and timeout',async()=>{
  let invoked=false;
  const missing=new SimulatorObserver({root:'/missing/microduck',checkExecutable:async()=>false,runner:async()=>{invoked=true;}});
  const absent=await missing.inspect('policies');
  assert.equal(absent.configured,false);
  assert.equal(absent.ok,false);
  assert.equal(invoked,false);
  const silent=new SimulatorObserver({root:'/official/microduck',checkExecutable:async()=>true,runner:async()=>({stdout:'',stderr:'Connection refused'})});
  const empty=await silent.inspect('status');
  assert.equal(empty.ok,false);
  assert.equal(empty.exitCode,0);
  assert.equal(empty.reason,'Official simulator returned no output');
  assert.match(empty.output,/Connection refused/);
  assert.equal((await silent.snapshot()).ready,false);
  const unavailable=new SimulatorObserver({root:'/official/microduck',checkExecutable:async()=>true,runner:async()=>({stdout:'robot     unavailable — cannot reach robotd\n',stderr:'Connection refused'})});
  const badStatus=await unavailable.inspect('status');
  assert.equal(badStatus.ok,false);
  assert.match(badStatus.reason,/could not reach robotd/);
  const degraded=new SimulatorObserver({root:'/official/microduck',checkExecutable:async()=>true,runner:async()=>({stdout:'robot     degraded\n  loop below target'})});
  assert.equal((await degraded.inspect('status')).ok,true);
  const unreachableVersion=new SimulatorObserver({root:'/official/microduck',checkExecutable:async()=>true,runner:async()=>({stdout:'robotctl 0.15.0\n  robotd unavailable — cannot reach robotd'})});
  assert.equal((await unreachableVersion.inspect('version')).ok,false);
  const timedOut=new SimulatorObserver({root:'/official/microduck',checkExecutable:async()=>true,runner:async()=>{throw Object.assign(new Error('timeout'),{killed:true,stdout:'partial JSON'});}});
  const timeout=await timedOut.inspect('policies');
  assert.equal(timeout.ok,false);
  assert.equal(timeout.reason,'Check timed out');
  assert.equal(timeout.verifiedRun,false);
  const nonzero=new SimulatorObserver({root:'/official/microduck',checkExecutable:async()=>true,runner:async()=>{throw Object.assign(new Error('daemon unavailable'),{code:7,stderr:'socket missing'});}});
  const failure=await nonzero.inspect('policies');
  assert.equal(failure.ok,false);
  assert.equal(failure.exitCode,7);
  assert.match(failure.output,/socket missing/);
  assert.equal((await nonzero.snapshot()).ready,false);
});
