import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createApp } from './app.js';
import { readStoredState } from './test-helpers.js';

test('local replies and likes are account-bound, persistent, and never robot evidence',async t=>{
  const folder=await mkdtemp(path.join(os.tmpdir(),'ducktown-social-'));
  t.after(()=>rm(folder,{recursive:true,force:true}));
  const dataFile=path.join(folder,'data.json');
  const {server}=await createApp({dataFile});
  server.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  const send=async(route,method,body,cookie)=>fetch(`${base}${route}`,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const register=async handle=>{
    const result=await send('/api/v1/auth/register','POST',{handle,password:`secure-test-${handle}-secret`});
    assert.equal(result.status,201);return result.headers.get('set-cookie').split(';')[0];
  };
  const alice=await register('social_alice'),bob=await register('social_bob');
  const created=await send('/api/v1/posts','POST',{text:'A build update'},alice);
  assert.equal(created.status,201);
  const {post}=await created.json(),likeRoute=`/api/v1/posts/${post.id}/like`,replyRoute=`/api/v1/posts/${post.id}/replies`;
  assert.equal((await send(likeRoute,'PUT')).status,401);
  assert.equal((await send(replyRoute,'POST',{text:'Hi'})).status,401);
  assert.equal((await send('/api/v1/posts/00000000-0000-0000-0000-000000000000/replies','GET')).status,404);
  assert.equal((await send('/api/v1/posts/00000000-0000-0000-0000-000000000000/like','PUT',undefined,bob)).status,404);
  assert.equal((await send(likeRoute,'PUT',undefined,bob)).status,200);
  assert.equal((await send(likeRoute,'PUT',undefined,bob)).status,200);
  let bobFeed=(await (await send('/api/v1/posts','GET',undefined,bob)).json()).posts[0];
  assert.equal(bobFeed.likes,1);
  assert.equal(bobFeed.viewerLiked,true);
  assert.equal((await (await send('/api/v1/posts','GET',undefined,alice)).json()).posts[0].viewerLiked,false);
  assert.equal((await send(replyRoute,'POST',{text:' '},bob)).status,400);
  assert.equal((await send(replyRoute,'POST',{text:'x'.repeat(401)},bob)).status,400);
  assert.equal((await send(replyRoute,'POST',{text:'a\u0000b'},bob)).status,400);
  assert.equal((await send(replyRoute,'POST',{text:'<script>alert(1)</script>',origin:'fake_telemetry'},bob)).status,201);
  const reply=(await (await send(replyRoute,'GET')).json()).replies[0];
  assert.equal(reply.origin,'human_reply');
  assert.equal(reply.text,'<script>alert(1)</script>');
  assert.equal(reply.handle,'social_bob');
  assert.equal(reply.origin==='simulator_telemetry_observed',false);
  bobFeed=(await (await send('/api/v1/posts','GET',undefined,bob)).json()).posts[0];
  assert.equal(bobFeed.replies,1);
  assert.equal((await send(likeRoute,'DELETE',undefined,bob)).status,200);
  assert.equal((await send(likeRoute,'DELETE',undefined,bob)).status,200);
  assert.equal((await (await send('/api/v1/posts','GET',undefined,bob)).json()).posts[0].likes,0);
  assert.equal((await fetch(`${base}${likeRoute}`,{method:'PUT',headers:{Cookie:bob,Origin:'http://evil.example'}})).status,403);
  const saved=readStoredState(dataFile);
  assert.equal(saved.postReplies.length,1);
  assert.equal(saved.postLikes.length,0);
  assert.equal(saved.postReplies[0].userId,saved.users.find(user=>user.handle==='social_bob').id);
});
